"""added duration_seconds

Revision ID: 3f2e7cddd653
Revises: a0b59b6e3122
Create Date: 2026-09-14 21:19:14.715165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2e7cddd653'
down_revision: Union[str, None] = 'a0b59b6e3122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'duration_seconds')
    # ### end Alembic commands ###
