"""added processed at

Revision ID: 7e66aa646246
Revises: a8bb270d225a
Create Date: 2026-09-14 21:01:20.735402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e66aa646246'
down_revision: Union[str, None] = 'a8bb270d225a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('state_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'state_id')
    op.drop_column('heartbeats', 'processed_at')
    # ### end Alembic commands ###
