"""worked on user and device models

Revision ID: 920780aed96c
Revises: f1bf81ad8d5c
Create Date: 2026-09-09 20:34:05.527393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920780aed96c'
down_revision: Union[str, None] = 'f1bf81ad8d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_user_api_keys_revoked_at'), 'user_api_keys', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.add_column('devices', sa.Column('installation_id', sa.Uuid(), nullable=False))
    op.add_column('devices', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('platform', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('os_version', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('machine_key', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('agent_version', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_devices_installation_id'), 'devices', ['installation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_installation_id'), table_name='devices')
    op.drop_column('devices', 'last_seen_at')
    op.drop_column('devices', 'is_active')
    op.drop_column('devices', 'agent_version')
    op.drop_column('devices', 'machine_key')
    op.drop_column('devices', 'os_version')
    op.drop_column('devices', 'platform')
    op.drop_column('devices', 'hostname')
    op.drop_column('devices', 'installation_id')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_revoked_at'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
