"""added user api keys

Revision ID: a8bb270d225a
Revises: 920780aed96c
Create Date: 2026-09-10 17:23:13.911453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bb270d225a'
down_revision: Union[str, None] = '920780aed96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_api_keys', sa.Column('device_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_api_keys_device_id'), 'user_api_keys', ['device_id'], unique=False)
    op.create_foreign_key(None, 'user_api_keys', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_user_api_keys_device_id'), table_name='user_api_keys')
    op.drop_column('user_api_keys', 'device_id')
    # ### end Alembic commands ###
