"""Initial migration

Revision ID: e79f1fd05222
Revises: 
Create Date: 2026-09-09 01:05:08.757114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79f1fd05222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('window_title', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_id')
    )
    op.create_index(op.f('ix_heartbeats_application'), 'heartbeats', ['application'], unique=False)
    op.create_index(op.f('ix_heartbeats_event_type'), 'heartbeats', ['event_type'], unique=False)
    op.create_index(op.f('ix_heartbeats_timestamp'), 'heartbeats', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_timestamp'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_event_type'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_application'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
