"""Worked on user tables

Revision ID: f1bf81ad8d5c
Revises: e79f1fd05222
Create Date: 2026-09-09 11:59:33.076472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bf81ad8d5c'
down_revision: Union[str, None] = 'e79f1fd05222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=False),
    sa.Column('window_title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_end_time'), 'sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_sessions_start_time'), 'sessions', ['start_time'], unique=False)
    op.add_column('heartbeats', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('heartbeats', sa.Column('device_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('heartbeats_local_id_key'), 'heartbeats', type_='unique')
    op.create_unique_constraint('uq_heartbeats_device_local', 'heartbeats', ['device_id', 'local_id'])
    op.create_foreign_key(None, 'heartbeats', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'heartbeats', 'devices', ['device_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heartbeats', type_='foreignkey')
    op.drop_constraint(None, 'heartbeats', type_='foreignkey')
    op.drop_constraint('uq_heartbeats_device_local', 'heartbeats', type_='unique')
    op.create_unique_constraint(op.f('heartbeats_local_id_key'), 'heartbeats', ['local_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('heartbeats', 'device_id')
    op.drop_column('heartbeats', 'user_id')
    op.drop_index(op.f('ix_sessions_start_time'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_end_time'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('devices')
    op.drop_table('users')
    # ### end Alembic commands ###
